package bots.hornet;

import arena.BotMath;
import robocode.HitByBulletEvent;
import robocode.HitWallEvent;
import robocode.Robot;
import robocode.ScannedRobotEvent;

/**
 * The reference bot that ships with the arena. It is a real opponent — beat it.
 *
 * You do not edit this file. Run `./tourney init <your-github-username> <BotName>`
 * to get your own copy in your own package, and edit that.
 *
 * Right now it drives back and forth, spins its gun looking for trouble, and
 * shoots whatever it finds. That is enough to win some battles and lose others.
 *
 * The README lists an upgrade for every chapter of the course. Start by changing
 * the three numbers below and watching what happens.
 */
public class HornetBot extends Robot {

    // ---- Try changing these first ----------------------------------------
    // How far the bot drives before turning around.
    private static final double MOVE_DISTANCE = 100;

    // How far it backs off after being hit.
    private static final double DODGE_DISTANCE = 50;

    // How sharply it turns away after being hit, in degrees.
    private static final double DODGE_TURN = 90;
    // ----------------------------------------------------------------------

    /**
     * The main loop. Robocode calls this once when the battle starts, and the
     * bot keeps doing whatever is inside the loop until the round ends.
     */
    @Override
    public void run() {
        while (true) {
            ahead(MOVE_DISTANCE);
            turnGunRight(360);
            back(MOVE_DISTANCE);
            turnGunRight(360);
        }
    }

    /**
     * Robocode calls this the moment your spinning gun sweeps across an enemy.
     * You did not call it — the framework did. That is an event handler, and
     * Chapter 8 is about why you get to write these at all.
     *
     * @param event what the radar saw
     */
    @Override
    public void onScannedRobot(ScannedRobotEvent event) {
        double power = BotMath.firePowerFor(event.getDistance());
        fire(power);
    }

    /**
     * Called when an enemy bullet connects. Standing still is how bots die,
     * so move somewhere else.
     *
     * @param event details of the hit, including which direction it came from
     */
    @Override
    public void onHitByBullet(HitByBulletEvent event) {
        double bearing = BotMath.normalizeBearing(event.getBearing());
        if (bearing > 0) {
            turnLeft(DODGE_TURN);
        } else {
            turnRight(DODGE_TURN);
        }
        ahead(DODGE_DISTANCE);
    }

    /**
     * Called when the bot drives into a wall. Back up and aim somewhere useful.
     *
     * @param event details of the collision
     */
    @Override
    public void onHitWall(HitWallEvent event) {
        back(DODGE_DISTANCE);
        turnRight(DODGE_TURN);
    }
}
